### ISSUE TITLE
Error installing the plugin

### ISSUE THREAD

**Issue by stijnelskens** [studioespresso/craft-mollie-payments#2]
When trying to install the plugin I get the following error:
  [InvalidArgumentException]
  Could not find a version of package studioespresso/craft-mollie-payments matching your minimum-stability (stable). Require it with an explicit version constraint a
  llowing its desired stability.

**Comment by janhenckens** [comment]
That's because the plugin only has beta releases for now, you can add `minimum-stability: beta` to your composer.json and then you should be able to install the plugin.

See the composer docs [here](https://getcomposer.org/doc/04-schema.md#minimum-stability)

I'll try to release a stable 1.0.0 somewhere this week since I'm not adding new feature for now.
